[auth]
enabled = true
site_url = "http://localhost:5173"
jwt_expiry = 315360000

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[auth.email.template.magic_link]
subject = "Your Elevate verification code"
content_path = "./supabase/templates/magic_link.html"
